# -*- coding: utf-8 -*-
"""Give every book its own shade of its family's colour.

Each genre family owns one accent hue. Within a family the books fan out
across a narrow band either side of it -- fourteen degrees of hue and eleven
points of lightness, centred on the family base, in canonical order -- so that
Leviticus and Deuteronomy are visibly not the same page while both are
obviously Torah.

Deliberately *not* a blend toward the family's secondary accent: the gospels
run lapis to gold, and forty per cent along that line is grey.

Reads the family bases straight out of the stylesheet, so changing a family
colour and re-running is enough. Idempotent: the generated block is delimited
and replaced wholesale.
"""
import io
import re

from _coords import G

HUE_SPAN = 14.0     # degrees, total, across a family
LIT_SPAN = 0.11     # lightness, total, across a family

P = 'index.html'
s = io.open(P, encoding='utf-8').read()


# ------------------------------------------------------------ colour maths
def hex_to_hsl(h):
    r, g, b = (int(h[i:i + 2], 16) / 255.0 for i in (1, 3, 5))
    mx, mn = max(r, g, b), min(r, g, b)
    lit = (mx + mn) / 2.0
    if mx == mn:
        return 0.0, 0.0, lit
    d = mx - mn
    sat = d / (mx + mn) if lit < 0.5 else d / (2.0 - mx - mn)
    if mx == r:
        hue = ((g - b) / d) % 6
    elif mx == g:
        hue = (b - r) / d + 2
    else:
        hue = (r - g) / d + 4
    return hue * 60.0, sat, lit


def hsl_to_hex(hue, sat, lit):
    hue = hue % 360
    c = (1 - abs(2 * lit - 1)) * sat
    x = c * (1 - abs((hue / 60.0) % 2 - 1))
    m = lit - c / 2
    rgb = [(c, x, 0), (x, c, 0), (0, c, x),
           (0, x, c), (x, 0, c), (c, 0, x)][int(hue // 60)]
    return '#%02X%02X%02X' % tuple(
        max(0, min(255, int(round((v + m) * 255)))) for v in rgb)


def shade(base, t):
    """`t` runs -0.5 (first book in the family) to +0.5 (last)."""
    hue, sat, lit = hex_to_hsl(base)
    return hsl_to_hex(hue + HUE_SPAN * t, sat, lit + LIT_SPAN * t)


# --------------------------------------------- family bases, per theme block
THEMES = [
    # (label, regex for the family rule, prefix each generated selector needs)
    ('light', r'\n\.chapter\[data-family="%s"\] \{(.*?)\}', ''),
    ('media', r'\n  :root:not\(\[data-theme="light"\]\) \.chapter\[data-family="%s"\] \{(.*?)\}',
     ':root:not([data-theme="light"]) '),
    ('attr', r'\n:root\[data-theme="dark"\] \.chapter\[data-family="%s"\] \{(.*?)\}',
     ':root[data-theme="dark"] '),
]

# canonical order within each family, straight from the spine's own ordering
fams = {}
for bid in sorted(G, key=lambda k: G[k]['o_canon']):
    fams.setdefault(G[bid]['fam'], []).append(bid)

blocks = {}
for label, pat, prefix in THEMES:
    lines = []
    for fam, books in sorted(fams.items()):
        if len(books) < 2:
            continue        # a family of one is already the family colour
        # Three families are dark in both modes and declare no themed override;
        # they keep the one base they have.
        m = re.search(pat % re.escape(fam), s, re.S)
        if m is None and label != 'light':
            m = re.search(THEMES[0][1] % re.escape(fam), s, re.S)
        assert m, 'no %s rule for family %s' % (label, fam)
        base = re.search(r'--k-accent:\s*(#[0-9A-Fa-f]{6})', m.group(1))
        assert base, 'no --k-accent in %s rule for %s' % (label, fam)
        n = len(books)
        for i, bid in enumerate(books):
            t = i / float(n - 1) - 0.5
            lines.append('%s#%s { --k-accent: %s; }'
                         % (prefix, bid, shade(base.group(1), t)))
    blocks[label] = lines

BEGIN = '/* ---------- per-book accent: a few degrees of hue and a little'
END = '/* ---------- end per-book accent ---------- */'

body = ([BEGIN,
         '   lightness either side of the family base, never a blend toward the',
         '   secondary accent (lapis toward gold lands on grey).',
         '   Generated by _accents.py -- edit the family colours, not these. ---------- */']
        + blocks['light']
        + ['@media (prefers-color-scheme: dark) {']
        + ['  ' + l for l in blocks['media']]
        + ['}']
        + blocks['attr']
        + [END])

# Delimited on both sides and replaced whole. An earlier version guessed the
# end of the run with a lookahead over accent-shaped lines, which stopped on
# the second line of its own comment and appended a duplicate block instead of
# replacing one.
start = s.index(BEGIN)
if END in s:
    end = s.index(END) + len(END)
else:
    # first run against a hand-written block: it ended at the next section
    end = s.index('\n\n/* =', start)

s = s[:start] + '\n'.join(body) + s[end:]
io.open(P, 'w', encoding='utf-8').write(s)
print('accents: %d books across %d families'
      % (len(blocks['light']), len([f for f in fams if len(fams[f]) > 1])))
