# voice.py — pull every editable block out of index.html as plain text, and put
# it back. For rewriting the prose in one pass without fighting the markup.
#
#   python voice.py extract      write voice.txt  (refuses to clobber; --force)
#   python voice.py check        show what merge would change, write nothing
#   python voice.py merge        write the edits back into index.html
#
# The contract: a block you have not touched is left byte-for-byte alone. Only
# blocks whose text actually changed get re-encoded, so an extract/merge with no
# edits in between is a guaranteed no-op on index.html.

import io, re, sys

PAGE = 'index.html'
FILE = 'voice.txt'

# ---- the blocks that hold prose. Everything else in the page is structure,
# generated by build_spine.py, or the base64 maps.
CONTAINERS = re.compile(
    r'<section class="chapter" id="(?P<bid>[^"]+)"'
    r'|<span class="sub">(?P<sub>.*?)</span>'
    r'|<div class="prose">(?P<prose>.*?)</div>'
    r'|<figcaption>(?P<figcaption>.*?)</figcaption>'
    r'|<div class="note">(?P<note>.*?)</div>'
    r'|<h3 class="sec">(?P<h3>.*?)</h3>'
    r'|<p class="vid-cap">(?P<vidcap>.*?)</p>'
    r'|<p class="loc-cap">(?P<loccap>.*?)</p>', re.S)

PARA = re.compile(r'<p(?: class="tag")?>(.*?)</p>', re.S)

# real characters in the text file, entities in the page
ENT = [('&amp;', '&'), ('&mdash;', '—'), ('&ndash;', '–'),
       ('&lsquo;', '‘'), ('&rsquo;', '’'),
       ('&ldquo;', '“'), ('&rdquo;', '”'),
       ('&hellip;', '…'), ('&middot;', '·'), ('&nbsp;', ' ')]


def decode(h):
    for ent, ch in ENT:
        h = h.replace(ent, ch)
    return re.sub(r'\s+', ' ', h).strip()


def encode(t):
    t = re.sub(r'&(?![a-zA-Z]+;|#\d+;)', '&amp;', t)   # bare & only
    for ent, ch in ENT[1:]:                            # & already done
        t = t.replace(ch, ent)
    return t


def leaves(s):
    """Every editable block, in document order, as (id, start, end) into s."""
    out, bid, seen = [], 'front', {}

    def add(key, a, b):
        n = seen[key] = seen.get(key, 0) + 1
        out.append(('%s.%s.%d' % (bid, key, n), a, b))

    for m in CONTAINERS.finditer(s):
        if m.group('bid'):
            bid, seen = m.group('bid'), {}
            continue
        for key in ('sub', 'figcaption', 'h3', 'vidcap', 'loccap'):
            if m.group(key) is not None:
                add(key, m.start(key), m.end(key))
        for key in ('prose', 'note'):
            inner = m.group(key)
            if inner is None:
                continue
            assert '<div' not in inner, 'nested div in %s of %s' % (key, bid)
            base = m.start(key)
            for p in PARA.finditer(inner):
                add(key, base + p.start(1), base + p.end(1))

    ids = [i for i, _, _ in out]
    assert len(ids) == len(set(ids)), 'duplicate block id'
    return out


HEAD = """\
# The Books — every editable block on the page, as plain text.
#
# Edit the text under each [id] and run:  python voice.py merge
# Then rebuild and check:                 python build_spine.py && python verify.py
#
# Rules
#   * Lines starting with # are comments. [id] lines are anchors — never edit one.
#   * A block is every line under its [id] until the next [id]. Wrap however you
#     like; the lines are joined with a single space, and blank lines are ignored.
#   * Type real characters — an em dash is —, a curly apostrophe is ’. They are
#     turned back into HTML entities for you.
#   * Inline tags are shown as-is and passed straight through. You will see
#     <b>, <em>, <a href="#book"> and <span class="sep">·</span>. Leave them
#     balanced. Do not add tags the stylesheet does not know about.
#   * A block you do not touch is left exactly as it was in the page.
#
# %d blocks, %d words.
"""


def load_page():
    return io.open(PAGE, encoding='utf-8').read()


def cmd_extract(force):
    s = load_page()
    ls = leaves(s)
    import os
    if os.path.exists(FILE) and not force:
        sys.exit('%s already exists — merge it first, or pass --force to '
                 'overwrite it and lose any edits in it.' % FILE)
    body = [HEAD % (len(ls), sum(len(decode(s[a:b]).split()) for _, a, b in ls))]
    for bid, a, b in ls:
        body.append('\n[%s]\n%s\n' % (bid, decode(s[a:b])))
    io.open(FILE, 'w', encoding='utf-8', newline='\n').write(''.join(body))
    print('%s: %d blocks, %d words' %
          (FILE, len(ls), sum(len(decode(s[a:b]).split()) for _, a, b in ls)))


def read_edits():
    txt = io.open(FILE, encoding='utf-8').read()
    edits, cur = {}, None
    for line in txt.split('\n'):
        if line.startswith('#'):
            continue
        m = re.match(r'^\[([^\]]+)\]\s*$', line)
        if m:
            cur = m.group(1)
            assert cur not in edits, 'duplicate [%s] in %s' % (cur, FILE)
            edits[cur] = []
        elif cur and line.strip():
            edits[cur].append(line.strip())
    return dict((k, ' '.join(v)) for k, v in edits.items())


def cmd_merge(write):
    s = load_page()
    ls = leaves(s)
    edits = read_edits()
    known = set(i for i, _, _ in ls)
    for k in edits:
        assert k in known, 'unknown block id [%s] — anchors must not be edited' % k
    missing = [i for i in known if i not in edits]
    if missing:
        print('note: %d block(s) absent from %s, left alone (%s%s)'
              % (len(missing), FILE, ', '.join(missing[:3]),
                 '...' if len(missing) > 3 else ''))

    changed = []
    for bid, a, b in ls:
        if bid not in edits:
            continue
        was, now = decode(s[a:b]), edits[bid]
        if was != now:
            changed.append((bid, a, b, was, now))

    if not changed:
        print('no changes.')
        return

    for bid, _, _, was, now in changed:
        print('\n[%s]\n  - %s\n  + %s'
              % (bid, was[:100] + ('...' if len(was) > 100 else ''),
                 now[:100] + ('...' if len(now) > 100 else '')))
    print('\n%d block(s) changed.' % len(changed))

    if not write:
        print('(check only — nothing written. run "merge" to apply.)')
        return
    for bid, a, b, was, now in reversed(changed):      # back to front: offsets hold
        s = s[:a] + encode(now) + s[b:]
    io.open(PAGE, 'w', encoding='utf-8', newline='').write(s)
    print('wrote %s. now: python build_spine.py && python verify.py' % PAGE)


if __name__ == '__main__':
    args = sys.argv[1:]
    cmd = args[0] if args else ''
    if cmd == 'extract':
        cmd_extract('--force' in args)
    elif cmd == 'check':
        cmd_merge(False)
    elif cmd == 'merge':
        cmd_merge(True)
    else:
        sys.exit(__doc__ or 'usage: voice.py extract | check | merge')
